= Update: What's New in Version 0.4.0

== Material design

To give 

== Development process

HubPress is moving away from developing in the https://github.com/HubPress/hubpress.io[hubpress.io] repository. 
To ensure the hubpress.io repository remains clean for new-adopters, development has shifted to https://github.com/HubPress/dev.hubpress.io[dev.hubpress.io].

The process to commit a change to HubPress is changed to the following:

. Fork https://github.com/HubPress/dev.hubpress.io
. If you have not done so, create an issue describing your fix.
. Create a branch in your forked repo and make the change.
. Open a Pull Request (PR), and summarise your changes, linking to the issue you created.

Once we receive your PR, we'll review your changes and then either accept them or ask for further changes before final acceptance.

The new repository is backed by Continuous Integration tasks that trigger automatically once a change to `/master` is detected.



== Theme

HubPress uses the professional-looking Ghost themes to allow you to personalise your Blog. It's been a year since release, so it's time for a couple of new looks. 

uno-zen::
  This theme is a simplified theme you can use for a more docs-site looking blog:
  * Great for long-form blogs, 
  * Looks great with pinned posts.
[theme-name]::
  Info about this theme.